List<Map<String, dynamic>> scriptsToExecute = [
  {
    '1.0.0' : [
      """CREATE TABLE "aplicativo" ( "id"	INTEGER, "nome"	TEXT, "key"	TEXT, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id") )""",
      """CREATE TABLE "aplicativo_versao" ( "id"	INTEGER, "id_aplicativo" INTEGER, "versao"	TEXT, "ehativo"	INTEGER, "data_limite"	TEXT, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_aplicativo") REFERENCES "aplicaivo"("id") )""",
      """CREATE TABLE "categoria" ( "id"	INTEGER, "id_pessoa_grupo"	INTEGER, "nome"	TEXT, "ehdeletado" INTEGER, "ehservico" INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id") )""",
      """CREATE TABLE "configuracao_app" ( "id"	INTEGER NOT NULL, "id_versao"	INTEGER NOT NULL, "data_atualizacao"	TEXT, PRIMARY KEY("id") )""",
      """CREATE TABLE "configuracao_geral" ( "id"	INTEGER NOT NULL, "id_pessoa_grupo"	INTEGER, "tem_servico" INTEGER, "ehservico_default" INTEGER, "ehmenu_classico" INTEGER, "data_atualizacao"	TEXT, "data_cadastro"	TEXT, PRIMARY KEY("id") )""",
      """CREATE TABLE "configuracao_pessoa" ( "id"	INTEGER NOT NULL, "id_pessoa"	INTEGER NOT NULL, "texto_cabecalho"	TEXT, "texto_rodape"	TEXT, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id") )""",
      """CREATE TABLE "contato" ( "id"	INTEGER, "id_pessoa"	INTEGER NOT NULL, "nome"	TEXT NOT NULL, "telefone1"	TEXT, "telefone2"	TEXT, "email"	TEXT, "ehprincipal"	INTEGER DEFAULT 0, "ehdeletado"	TEXT NOT NULL DEFAULT 0, "data_cadastro"	TEXT NOT NULL, "data_atualizacao"	TEXT NOT NULL, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id") )""",
      """CREATE TABLE "endereco" ( "id"	INTEGER NOT NULL, "id_pessoa"	INTEGER NOT NULL, "cep"	TEXT, "logradouro"	TEXT, "numero"	TEXT, "complemento"	TEXT, "bairro"	TEXT, "municipio"	TEXT, "estado"	TEXT, "ibge_municipio"	TEXT, "apelido"	TEXT, "pais"	TEXT NOT NULL, "ehdeletado"	INTEGER NOT NULL DEFAULT 0, "data_cadastro"	TEXT NOT NULL, "data_atualizacao"	TEXT NOT NULL, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id") )""",
      """CREATE TABLE "estoque" ( "id"	INTEGER NOT NULL, "id_pessoa"	INTEGER NOT NULL, "id_pessoa_grupo"	INTEGER NOT NULL, "id_produto"	INTEGER NOT NULL, "id_variante"	INTEGER NOT NULL, "estoque_total"	REAL NOT NULL DEFAULT 0, "et1"	REAL DEFAULT 0, "et2"	REAL DEFAULT 0, "et3"	REAL DEFAULT 0, "et4"	REAL DEFAULT 0, "et5"	REAL DEFAULT 0, "et6"	REAL DEFAULT 0, "et7"	REAL DEFAULT 0, "et8"	REAL DEFAULT 0, "et9"	REAL DEFAULT 0, "et10"	REAL DEFAULT 0, "et11"	REAL DEFAULT 0, "et12"	REAL DEFAULT 0, "et13"	REAL DEFAULT 0, "et14"	REAL DEFAULT 0, "et15"	REAL DEFAULT 0, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id"), PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id"), FOREIGN KEY("id_variante") REFERENCES "variante"("id") )""",
      """CREATE TABLE "cupom_layout" ("id"	INTEGER, "nome"	TEXT, "layout"	TEXT, "tamanho_papel"	INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT )""",
      """CREATE TABLE "grade" ( "id"	INTEGER, "id_pessoa_grupo"	INTEGER, "nome"	TEXT, "t1"	TEXT, "t2"	TEXT, "t3"	TEXT, "t4"	TEXT, "t5"	TEXT, "t6"	TEXT, "t7"	TEXT, "t8"	TEXT, "t9"	TEXT, "t10"	TEXT, "t11"	TEXT, "t12"	TEXT, "t13"	TEXT, "t14"	TEXT, "t15"	TEXT, "ehdeletado"	INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id") )""",
      """CREATE TABLE "modulo" ( "id"	INTEGER NOT NULL, "nome"	TEXT NOT NULL, "ehativo"	INTEGER NOT NULL DEFAULT 0, "data_cadastro"	TEXT NOT NULL, "data_atualizacao"	TEXT NOT NULL, PRIMARY KEY("id") )""",
      """CREATE TABLE "modulo_grupo" ( "id"	INTEGER NOT NULL, "nome"	TEXT NOT NULL, "valor"	REAL NOT NULL DEFAULT 0, "ehativo"	INTEGER NOT NULL DEFAULT 0, "data_cadastro"	TEXT NOT NULL, "data_atualizacao"	TEXT NOT NULL, PRIMARY KEY("id") )""",
      """CREATE TABLE "modulo_grupo_item" ( "id"	INTEGER NOT NULL, "id_modulo_grupo"	INTEGER NOT NULL, "id_modulo"	INTEGER NOT NULL DEFAULT 0, "data_cadastro"	TEXT NOT NULL, "data_atualizacao"	TEXT NOT NULL, PRIMARY KEY("id") )""",
      """CREATE TABLE "movimento" ( "id_app"	INTEGER PRIMARY KEY AUTOINCREMENT, "id"	INTEGER, "id_pessoa"	INTEGER, "id_cliente"	INTEGER, "id_vendedor"	INTEGER, "id_transacao"	INTEGER, "id_terminal"	INTEGER, "ehorcamento"	INTEGER, "ehcancelado"	INTEGER, "ehsincronizado"	INTEGER, "ehfinalizado"	INTEGER, 
        "valor_total_bruto_produto" REAL,
        "valor_total_bruto_servico" REAL,
        "valor_total_desconto_item_produto" REAL,
        "valor_total_desconto_item_servico" REAL,
        "valor_total_liquido_produto" REAL,
        "valor_total_liquido_servico" REAL,
        "valor_total_bruto"	REAL, "valor_total_desconto"	REAL, "valor_total_liquido"	REAL, "valor_total_desconto_item"	REAL, "valor_troco"	REAL, "total_itens"	INTEGER, "total_quantidade"	REAL, "observacao" TEXT, "data_movimento"	TEXT, "data_fechamento"	TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_transacao") REFERENCES "transacao"("id"), FOREIGN KEY("id_terminal") REFERENCES "terminal"("id"), FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id") )""",
      """CREATE TABLE "movimento_caixa" ( "id_app"	INTEGER PRIMARY KEY AUTOINCREMENT, "id"	INTEGER, "id_terminal"	INTEGER, "data_abertura"	TEXT, "data_fechamento"	TEXT, "valor_abertura"	REAL, "venda_total_valor_bruto"	REAL, "venda_total_valor_desconto"	REAL, "venda_total_valor_acrescimo"	REAL, "venda_total_valor_liquido"	REAL, "venda_total_valor_cancelado"	REAL, "venda_total_valor_desconto_item"	REAL, "venda_total_quantidade"	REAL, "venda_total_quantidade_cancelada"	REAL, "venda_total_item"	INTEGER, "venda_total_boleto_fechado"	INTEGER, "venda_total_boleto_pedido"	INTEGER, "venda_total_boleto_cancelado"	INTEGER, "devolucao_total_valor_bruto"	REAL, "devolucao_total_valor_desconto"	REAL, "devolucao_total_valor_acrescimo"	REAL, "devolucao_total_valor_liquido"	REAL, "devolucao_total_valor_cancelado"	REAL, "devolucao_total_quantidade"	REAL, "devolucao_total_quantidade_cancelada"	REAL, "devolucao_total_item"	INTEGER, "devolucao_total_boleto_fechado"	INTEGER, "devolucao_total_boleto_cancelado"	INTEGER, "saida_total_valor_bruto"	REAL, "saida_total_valor_desconto"	REAL, "saida_total_valor_acrescimo"	REAL, "saida_total_valor_liquido"	REAL, "saida_total_valor_cancelado"	REAL, "saida_total_quantidade"	REAL, "saida_total_quantidade_cancelada"	REAL, "saida_total_item"	INTEGER, "saida_total_boleto_fechado"	INTEGER, "saida_total_boleto_cancelado"	INTEGER, "entrada_total_valor_bruto"	REAL, "entrada_total_valor_desconto"	REAL, "entrada_total_valor_acrescimo"	REAL, "entrada_total_valor_liquido"	REAL, "entrada_total_valor_cancelado"	REAL, "entrada_total_quantidade"	REAL, "entrada_total_quantidade_cancelada"	REAL, "entrada_total_item"	INTEGER, "entrada_total_boleto_fechado"	INTEGER, "entrada_total_boleto_cancelado"	INTEGER, "data_atualizacao"	TEXT, FOREIGN KEY("id_terminal") REFERENCES "terminal"("id"))""",
      """CREATE TABLE "movimento_caixa_parcela" ( "id_app"	INTEGER PRIMARY KEY AUTOINCREMENT, "id"	INTEGER, "id_app_movimento_caixa"	INTEGER, "id_movimento_caixa"	INTEGER, "id_tipo_pagamento"	INTEGER, "data"	TEXT, "descricao"	TEXT, "valor"	REAL, "observacao"	TEXT, ehabertura INTEGER, ehreforco INTEGER, ehretirada INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT )""",
      """CREATE TABLE "movimento_cliente" ( "id_app"	INTEGER PRIMARY KEY AUTOINCREMENT, "id"	INTEGER, "id_pessoa"	INTEGER, "id_cliente"	INTEGER, "id_app_movimento"	INTEGER, "id_movimento"	INTEGER, "id_tipo_pagamento"	INTEGER, "data"	TEXT, "valor"	REAL, "descricao"	TEXT, "saldo"	REAL, "observacao" TEXT, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id"), FOREIGN KEY("id_movimento") REFERENCES "movimento"("id"), FOREIGN KEY("id_tipo_pagamento") REFERENCES "tipo_pagamento"("id"), FOREIGN KEY("id_app_movimento") REFERENCES "movimento"("id_app") )""",
      """CREATE TABLE "movimento_item" ( "id_app"	INTEGER PRIMARY KEY AUTOINCREMENT, "id"	INTEGER, "id_movimento_app"	INTEGER, "id_movimento"	INTEGER, "id_produto"	INTEGER, "id_variante"	INTEGER, "grade_posicao"	INTEGER, "sequencial"	INTEGER, "quantidade"	REAL, "preco_custo"	REAL, "preco_tabela"	REAL, "preco_vendido"	REAL, "total_bruto"	REAL, "prazo_entrega" TEXT, "garantia" TEXT, "observacao" TEXT, "observacao_interna" TEXT, "total_liquido"	REAL, "total_desconto"	REAL, "ehdeletado"	INTEGER, "ehservico" INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_produto") REFERENCES "produto"("id"), FOREIGN KEY("id_variante") REFERENCES "variante"("id"), FOREIGN KEY("id_movimento") REFERENCES "movimento"("id") )""",
      """CREATE TABLE "movimento_parcela" ( "id_app"	INTEGER PRIMARY KEY AUTOINCREMENT, "id"	INTEGER, "id_movimento_app"	INTEGER, "id_movimento"	INTEGER, "id_tipo_pagamento"	INTEGER, "valor"	REAL, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_tipo_pagamento") REFERENCES "tipo_pagamento"("id"), FOREIGN KEY("id_movimento") REFERENCES "movimento"("id") )""",
      """CREATE TABLE "pessoa" ( "id"	INTEGER NOT NULL, "id_pessoa_grupo"	INTEGER NOT NULL, "razao_nome"	TEXT, "fantasia_apelido"	TEXT, "cnpj_cpf"	TEXT, "ie_rg"	TEXT, "im"	TEXT, "ehfisica"	INTEGER DEFAULT 0, "ehcliente"	INTEGER DEFAULT 0, "ehfornecedor"	INTEGER DEFAULT 0, "ehloja"	INTEGER DEFAULT 0, "ehrevenda" INTEGER DEFAULT 0, "ehusuario" INTEGER DEFAULT 0, "ehvendedor" INTEGER DEFAULT 0, "ehdeletado"	INTEGER DEFAULT 0, "id_pessoa"	INTEGER, "password"	TEXT, "id_facebook"	TEXT, "id_google"	TEXT, "data_cadastro" TEXT, "data_atualizacao" TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id") )""",
      """CREATE TABLE "pessoa_grupo" ( "id"	INTEGER NOT NULL, "nome"	TEXT, "id_pessoa"	INTEGER NOT NULL, "ehdeletado" INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id") )""",
      """CREATE TABLE "pessoa_modulo" ( "id"	INTEGER NOT NULL, "id_pessoa"	INTEGER NOT NULL, "id_modulo_grupo"	INTEGER NOT NULL, "valor"	REAL NOT NULL DEFAULT 0, "ehativo"	INTEGER NOT NULL DEFAULT 0, "ehdemonstracao"	INTEGER NOT NULL DEFAULT 0, "data_final_demonstracao"	TEXT NOT NULL, "data_cadastro"	TEXT NOT NULL, "data_atualizacao"	TEXT NOT NULL, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id"), FOREIGN KEY("id_modulo_grupo") REFERENCES "modulo_grupo"("id") )""",
      """CREATE TABLE "preco_tabela" ( "id"	INTEGER, "id_pessoa_grupo"	INTEGER, "nome"	TEXT, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id") )""",
      """CREATE TABLE "preco_tabela_item" ( "id"	INTEGER, "id_preco_tabela"	INTEGER, "id_produto"	INTEGER, "preco"	REAL, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_preco_tabela") REFERENCES "preco_tabela"("id"), FOREIGN KEY("id_produto") REFERENCES "produto"("id") )""",
      """CREATE TABLE "variante" ( "id"	INTEGER, "id_pessoa_grupo"	INTEGER, "nome"	TEXT, "icone"	TEXT, "iconecor"	TEXT, "ehdeletado" INTEGER NOT NULL, "nome_avatar" TEXT, "tem_imagem" INTEGER NOT NULL DEFAULT 0, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id") )""",
      """CREATE TABLE "produto" ( "id" INTEGER, "id_pessoa_grupo" INTEGER, "id_aparente" TEXT, "id_categoria" INTEGER, "id_grade" INTEGER, "nome" TEXT, "preco_custo" REAL, "ehativo" INTEGER, "iconecor" TEXT, "ehdeletado" INTEGER NOT NULL, "ehservico" INTEGER, "data_cadastro" TEXT, "data_atualizacao" TEXT, FOREIGN KEY("id_grade") REFERENCES "grade"("id"), PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id"), FOREIGN KEY("id_categoria") REFERENCES "categoria"("id") )""",
      """CREATE TABLE "produto_imagem" ( "id"	INTEGER, "id_produto"	INTEGER, "imagem"	TEXT, "ehdeletado" INTEGER NOT NULL, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_produto") REFERENCES "produto"("id") )""",
      """CREATE TABLE "produto_variante" ( "id"	INTEGER, "id_produto"	INTEGER, "id_variante"	INTEGER, "ehdeletado" INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_produto") REFERENCES "produto"("id"), FOREIGN KEY("id_variante") REFERENCES "variante"("id") )""",
      """CREATE TABLE "produto_codigo_barras" ( "id"	INTEGER, "id_produto"	INTEGER, "id_variante"	INTEGER, "grade_posicao" INTEGER, "codigo_barras" TEXT, ehdeletado INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_produto") REFERENCES "produto"("id"), FOREIGN KEY("id_variante") REFERENCES "variante"("id") )""",
      """CREATE TABLE "terminal" ( "id"	INTEGER, "id_pessoa"	INTEGER, "id_transacao"	INTEGER, "id_device"	TEXT, "nome"	TEXT, "mercadopago_id_terminal" TEXT, "mercadopago_qr_code" TEXT, "ehdeletado"	INTEGER, "tem_picpay"	INTEGER, "tem_controle_caixa"	INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_pessoa") REFERENCES "pessoa_old"("id"), PRIMARY KEY("id"), FOREIGN KEY("id_transacao") REFERENCES "transacao"("id") )""",
      """CREATE TABLE "terminal_impressora" ("id"	INTEGER NOT NULL, "id_pessoa"	INTEGER NOT NULL, "id_terminal"	INTEGER NOT NULL,"id_cupom_layout"	INTEGER, "nome"	TEXT, "tipo_impressora"	TEXT, "mac_address"	TEXT, "ip"	TEXT, "texto_cabecalho" TEXT, "texto_rodape" TEXT, "ehdeletado"	INTEGER DEFAULT 0, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id"), FOREIGN KEY("id_terminal") REFERENCES "terminal"("id"), FOREIGN KEY("id_cupom_layout") REFERENCES "cupom_layout"("id")) """,
      """CREATE TABLE "tipo_pagamento" ( "id"	INTEGER, "id_pessoa_grupo"	INTEGER, "nome"	TEXT, "icone"	TEXT, "ehdinheiro"	INTEGER, "ehfiado"	INTEGER, "ehqrcode"	INTEGER, "ehdeletado"	INTEGER, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id") )""",
      """CREATE TABLE "transacao" ("id"	INTEGER, "id_pessoa_grupo" INTEGER, "id_preco_tabela" INTEGER, "nome" TEXT, "tipo_estoque" INTEGER, "tem_pagamento"	INTEGER, "tem_vendedor"	INTEGER, "tem_cliente"	INTEGER, "desconto_percentual"	REAL, "ehdeletado"	INTEGER NOT NULL, "data_cadastro"	TEXT, "data_atualizacao"	TEXT, PRIMARY KEY("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id"), FOREIGN KEY("id_preco_tabela") REFERENCES "preco_tabela"("id"))""",
      """CREATE TABLE "tutorial" ("id" INTEGER, "id_pessoa_grupo"	INTEGER, "id_pessoa" INTEGER, "modulo" TEXT, "ehconcluido"	INTEGER, "passo" INTEGER, "ehvisualizado"	INTEGER, "data_cadastro" TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id") )""",
      """CREATE TABLE "log_erro" ("id_app" INTEGER PRIMARY KEY AUTOINCREMENT, "id" INTEGER, "id_pessoa_grupo"	INTEGER, "id_pessoa" INTEGER, "nome_arquivo" TEXT, "nome_funcao" TEXT, "error" TEXT, "stacktrace" TEXT, "object" TEXT, "query" TEXT, "ehsincronizado" INTEGER, "data_cadastro" TEXT, "data_atualizacao"	TEXT, FOREIGN KEY("id_pessoa") REFERENCES "pessoa"("id"), FOREIGN KEY("id_pessoa_grupo") REFERENCES "pessoa_grupo"("id") )""",


      """CREATE INDEX "idx_contato_data_atualizacao" ON "contato" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_contato_data_cadastro" ON "contato" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_contato_email" ON "contato" ("email"	ASC)""",
      """CREATE INDEX "idx_contato_nome" ON "contato" ("nome"	ASC)""",
      """CREATE INDEX "idx_endereco_cadastro" ON "endereco" ("data_cadastro"  ASC)""",
      """CREATE INDEX "idx_endereco_data_atualizacao" ON "endereco" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_endereco_logradouro" ON "endereco" ("logradouro"	ASC)""",
      """CREATE INDEX "idx_grade_data_atualizacao" ON "grade" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_grade_data_cadastro" ON "grade" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_grade_nome" ON "grade" ("nome"	ASC)""",
      """CREATE INDEX "idx_modulo_data_atualizacao" ON "modulo" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_modulo_data_cadastro" ON "modulo" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_modulo_nome" ON "modulo" ("nome"	ASC)""",
      """CREATE INDEX "idx_movimento_01" ON "movimento" ("id_cliente"	ASC,"data_movimento"	ASC)""",
      """CREATE INDEX "idx_movimento_caixa_data_abertura" ON "movimento_caixa" ("data_abertura"	ASC)""",
      """CREATE INDEX "idx_movimento_caixa_data_atualizacao" ON "movimento_caixa" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_movimento_caixa_data_fechamento" ON "movimento_caixa" ("data_fechamento"	ASC)""",
      """CREATE INDEX "idx_movimento_caixa_parcela_data" ON "movimento_caixa_parcela" ("data"	ASC)""",
      """CREATE INDEX "idx_movimento_caixa_parcela_data_atualizacao" ON "movimento_caixa_parcela" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_movimento_caixa_parcela_data_cadastro" ON "movimento_caixa_parcela" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_movimento_cliente_data" ON "movimento_cliente" ("data"	ASC)""",
      """CREATE INDEX "idx_movimento_cliente_data_atualizacao" ON "movimento_cliente" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_movimento_cliente_data_cadastro" ON "movimento_cliente" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_movimento_data_atualizacao" ON "movimento" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_movimento_data_fechamento" ON "movimento" ("data_fechamento"	ASC)""",
      """CREATE INDEX "idx_movimento_data_movimento" ON "movimento" ("data_movimento"	ASC)""",
      """CREATE INDEX "idx_movimento_item_data_atualizacao" ON "movimento_item" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_movimento_item_data_cadastro" ON "movimento_item" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_preco_tabela_data_cadastro" ON "preco_tabela" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_produto_data_atualizacao" ON "produto" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_produto_data_cadastro" ON "produto" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_produto_imagem_data_atualizacao" ON "produto_imagem" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_produto_imagem_data_cadastro" ON "produto_imagem" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_produto_imagem_imagem" ON "produto_imagem" ("imagem"	ASC)""",
      """CREATE INDEX "idx_produto_variante_data_atualizacao" ON "produto_variante" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_produto_variante_data_cadastro" ON "produto_variante" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_terminal_data_atualizacao" ON "terminal" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_terminal_data_cadastro" ON "terminal" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_tipo_pagamento_data_atualizacao" ON "tipo_pagamento" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_tipo_pagamento_data_cadastro" ON "tipo_pagamento" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_tipo_pagamento_nome" ON "tipo_pagamento" ("nome"	ASC)""",
      """CREATE INDEX "idx_transacao_data_atualizacao" ON "transacao" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_transacao_data_cadastro" ON "transacao" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_transacao_nome" ON "transacao" ("nome"	ASC)""",
      """CREATE INDEX "idx_variante_data_atualizacao" ON "variante" ("data_atualizacao"	ASC)""",
      """CREATE INDEX "idx_variante_data_cadastro" ON "variante" ("data_cadastro"	ASC)""",
      """CREATE INDEX "idx_variante_nome" ON "variante" ("nome"	ASC)""",
      """CREATE INDEX "idx_categoria_01" ON "categoria" ( "nome"	ASC, "data_cadastro"	ASC)""",
      """CREATE INDEX "idx_contato_01" ON "contato" ( "id"	ASC, "nome"	ASC)""",
      """CREATE INDEX "idx_endereco_apelido" ON "endereco" ( "apelido"	ASC)""",
      """CREATE INDEX "idx_grade_01" ON "grade" ( "id"	ASC, "nome"	ASC)""",
      """CREATE INDEX "idx_pessoa_01" ON "pessoa" ( "id"	ASC, "fantasia_apelido"	ASC)""",
      """CREATE INDEX "idx_preco_tabela_01" ON "preco_tabela" ( "id"	ASC, "nome"	ASC)""",
      """CREATE INDEX "idx_produto_nome" ON "produto" ( "nome"	ASC)""",
      """CREATE INDEX "idx_variante_01" ON "variante" ( "id"	ASC, "nome"	ASC)""",
      """CREATE INDEX "idx_terminal_nome" ON "terminal" ( "nome"	ASC)""",
      """CREATE INDEX "idx_tipo_pagamento_01" ON "tipo_pagamento" ( "id"	ASC, "nome"	ASC)""",
      """CREATE INDEX "idx_transacao_01" ON "transacao" ( "id"	ASC, "tipo_estoque"	ASC)""",
      """CREATE INDEX "idx_movimento_item_01" ON "movimento_item" ( "ehdeletado"	ASC, "id_movimento_app"	ASC)""",
      """CREATE INDEX "idx_movimento_parcela_id_movimento_app" ON "movimento_parcela" ( "id_movimento_app"	ASC)""",
      """CREATE INDEX "idx_movimento_caixa_01" ON "movimento_caixa" ( "data_abertura"	ASC, "data_fechamento"	ASC)""",
      "INSERT INTO configuracao_app (id, id_versao, data_atualizacao) values (1, '1.0.0', '${DateTime.now().toIso8601String()}')"
    ]
  },
  // {
  //   '1.0.1' : [
  //     "ALTER TABLE variante ADD COLUMN ehdeletado INTEGER NOT NULL DEFAULT 0",
  //     "ALTER TABLE variante ADD COLUMN nome_avatar TEXT",
  //     "ALTER TABLE variante ADD COLUMN possui_imagem INTEGER NOT NULL DEFAULT 0",
  //     "UPDATE configuracao_app SET id_versao = '1.0.1', data_atualizacao = '${DateTime.now().toIso8601String()}' where id = 1"
  //   ]
  // },
  // {
  //   '1.0.2': [
  //     "ALTER TABLE variante ADD COLUMN update_certo INTEGER NOT NULL DEFAULT 777",
  //     "UPDATE configuracao_app SET id_versao = '1.0.2', data_atualizacao = '${DateTime.now().toIso8601String()}' where id = 1"
  //   ]
  // },
];